### PR TITLE
set ensureThatRecordExists to false for surveyLink

### PR DESCRIPTION
**Pull request by takuy**
Apparently, my changes in #29 caused an issue. `REDCap::getSurveyLink()`, pre-version 10.6.1 (lowest I could find), checks if the record exists in a specific arm and will not proceed. In newer versions of REDCap, `REDCap::getSurveyLink()` introduced `$ensureThatRecordExists` parameter that skips that check. This PR checks the version of REDCap in use and sets that parameter to false. 

Otherwise, passthrough links will fail if the record doesn't already exist in that arm. 

The previous implementation of the surveyPassthru functionality did not have this problem. There is no fix for versions before 10.6.1 at the moment.
 
I'm not sure of the best way of handling it for older versions; maybe raise the minimum version for the EM?

### CODE REVIEW

**Comment by takuy** [comment]
Hi @knil-maloon - any chance you can look at this? We can't keep our modules updated (and the module working) without a fix like this.

**Comment by takuy** [comment]
@knil-maloon - hope you see this soon. We're behind on updates and would like to get this fixed. Let me know if you can accept this PR or some variant to make sure `getSurveyLink(... $ensureThatRecordExists = false)` gets set.

**Comment by scottjpearson** [comment]
Hey takuy! I'm filling in for Eva while she's on maternity leave (yay!). We have need to do a minor release, so I'm going to try to throw your PR in there, too.

However, there are a few minor issues:
- First, version 2.4.6 has more instances of REDCap::getSurveyLink being called than before. It might even make sense to centralize these calls to the REDCap class into one central function call within the ExtMod.
- Second, I want to make sure that the project_id is being passed into each call. Right now, you have it passed in as an empty string instead.
- Finally, REDCap:: getSurveyReturnCode should have a final parameter passed as an $instance. Version 2.4.6 handles this correctly.

If you can make these changes quickly, I'm happy to push these along the formal review process. If not, we can wait until Eva returns near the end of February.

**Comment by takuy** [comment]
> Hey takuy! I'm filling in for Eva while she's on maternity leave (yay!). We have need to do a minor release, so I'm going to try to throw your PR in there, too.
> 
> However, there are a few minor issues:
> 
> * First, version 2.4.6 has more instances of REDCap::getSurveyLink being called than before. It might even make sense to centralize these calls to the REDCap class into one central function call within the ExtMod.
> * Second, I want to make sure that the project_id is being passed into each call. Right now, you have it passed in as an empty string instead.
> * Finally, REDCap:: getSurveyReturnCode should have a final parameter passed as an $instance. Version 2.4.6 handles this correctly.
> 
> If you can make these changes quickly, I'm happy to push these along the formal review process. If not, we can wait until Eva returns near the end of February.

Hey, I noticed the min version of REDCap for this plugin was changed to 13.x - so I actually removed the version check, since have the option of calling just the proper version of getSurveyLink. I also updated to include the project_id and instance where applicable. So, now it's a super small change! 

Hope it looks good to you, would love to get this merged in so we can update our instance. 

Thanks

**Review by scottjpearson — APPROVED** [review]

**Comment by scottjpearson** [comment]
Great! Give us a couple days to run routine tests and get it approved. It should be on the REDCap Repo early next week. Thanks!

**Pull request merged**
