### PR TITLE
Review

### PR DESCRIPTION
**Pull request by knil-maloon**
New variable to avoid looping too much on the queued emails

### CODE REVIEW

**Comment by scottjpearson** [comment]
I'm confused about function isThisAlertCheckedToSendToday. I was assuming it was an array, but you are sending it into a strtotime() function, which requires a string. Is this intended? I couldn't figure out from the code alone and thought I should ask...

**Review by scottjpearson — CHANGES_REQUESTED** [review]
Other than the comment, I will approve. After reading the rest of the code, I believe this comment identifies an error, but I'm happy to be wrong.

> I'm confused about function isThisAlertCheckedToSendToday. I was assuming it was an array, but you are sending it into a strtotime() function, which requires a string. Is this intended? I couldn't figure out from the code alone and thought I should ask...

**Comment by knil-maloon** [comment]
> isThisAlertCheckedToSendToday

I'm not sure I understand what you mean. What the function does is it checks if the date of alert_last_sent is the same as today as it means the code has already checked all those queued emails and shouldn't do it anymore.

**Review by scottjpearson — APPROVED** [review]
Never mind. I was looking at this line, but now see that you're referencing an element. I missed the brackets. My mistake.

`$alert_last_sent = $this->getProjectSetting("alert-last-sent", $projectId)[$alert];`

Approved!

**Pull request merged**
