### PR TITLE
ordered sent records displayed

### PR DESCRIPTION
**Pull request by knil-maloon**

### CODE REVIEW

**Review by scottjpearson — CHANGES_REQUESTED** [review]
Shouldn't line 1322 have an implode("," $scheduled_records_activated)?

**Comment by scottjpearson** [comment]
I'm confused. Then why is it being run in a sort() a line or two earlier?

**Comment by knil-maloon** [comment]
Sorry I was looking at the wrong spot...
Fixed and saw scheduled also needed to be changed

**Review by scottjpearson — APPROVED** [review]
I'm approving this with a note. \System::increaseMaxExecTime() in REDCap is how I usually adjust this time. Rob sets the max_execution_time value in php.ini, too, before running set_time_limit(). If you run into troubles with this section of code, I'd suggest revising there.

`        // Increase PHP web server max_execution_time value in seconds, if lower (if higher, then leave as is)
        public static function increaseMaxExecTime($seconds)
        {       
                if (isinteger($seconds) && ini_get('max_execution_time') < $seconds) {
                        ini_set('max_execution_time', $seconds);
                        @set_time_limit($seconds);
                }
        }
`

**Pull request merged**
