### PR TITLE
Bug fixes and additions

### PR DESCRIPTION
**Pull request by knil-maloon**
- There was a bug fix on permanently delete where it was not deleting the file.
- Bug fix on file save for new alerts where the index was always 0.
- Added file size display next to file name.
- Added file size check to ensure it's not bigger.
- Added javascript error display on a function.
- New function to manage bytes.

### CODE REVIEW

**Review by scottjpearson — APPROVED** [review]
Functionally, this works, so I'm approving.

I have only one suggested improvement, which occasionally helps me avoid a mistake. In modern JS, `const` and `let` are to be preferred to `var`. I try to update my code when I see `var`, but `var` still works in browsers.

To assist in case you didn't know the rules, `let` means modifiable, but `const` does not - for anything EXCEPT hashes and arrays. Hashes and arrays can use `const` to assign them since, beneath the hood, they involve pointers to elements.

**Comment by scottjpearson** [comment]
I also notice a trivial conflict that should not require my re-approval, just some editing.

**Comment by knil-maloon** [comment]
Oh good to know! I hope I remember the let/const versus var!

**Comment by knil-maloon** [comment]
I'll merge tomorrow and check the conflict. Thanks!

**Pull request merged**
